mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.myspring.demo.mybatis.entity
server:
    port: 8080
spring:
    application:
        name: demo
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: 123456
        url: jdbc:mysql://localhost:3306/myspringboot?serverTimezone=UTC
        username: root
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql